name: Desplegar a producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar a servidor de producción
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio al espacio de trabajo
        uses: actions/checkout@v3

      - name: Desplegar vía SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            echo "Abriendo directorio del proyecto..."
            cd /var/www/laravel
            echo "Haciendo pull de la última versión desde repositorio..."
            git pull origin main
            echo "Instalando dependencias de PHP..."
            composer install --no-interaction --prefer-dist --optimize-autoloader
            echo "Limpiando cache..."
            php artisan optimize:clear
            echo "Ejecutando migraciones..."
            php artisan migrate --force
            echo "Instalando dependencias de Node.js..."
            /root/.nvm/versions/node/v20.17.0/bin/npm install
            echo "Compilando assets..."
            /root/.nvm/versions/node/v20.17.0/bin/npm run build
            echo "Despliegue completado."
