name: Desplegar a producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar a servidor de producción
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio al espacio de trabajo
        uses: actions/checkout@v3

      - name: Desplegar vía SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            echo "Iniciando despliegue..."
            echo "Abriendo directorio del proyecto..."
            export PATH="/home/tis2/.nvm/versions/node/v20.19.1/bin:$PATH"
            git config --global --add safe.directory /var/www/laravel
            cd /var/www/laravel
            chmod +x deploy.sh
            ./deploy.sh
